package com.localhost.cadastrodealunosv2.view;

import com.localhost.cadastrodealunosv2.controller.AlunoController;
import com.localhost.cadastrodealunosv2.model.AlunoModel;
import javax.swing.JOptionPane;

/**
 * @author Diego Barbosa da Silva
 */
public class AlunoView extends javax.swing.JFrame {
    
    // Aluno
    AlunoModel alunoModel = new AlunoModel();
    AlunoController alunoController = new AlunoController();
    
    // Tela
    private MainView mainView;
    
    /**
     * Creates new form AlunoView
     */
    public AlunoView(MainView mainView) {
        initComponents();
        this.mainView = mainView;
    }

    public AlunoView() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSalvarAluno = new javax.swing.JButton();
        jtfNomeAluno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnCancelarAluno = new javax.swing.JButton();
        jtfIdAluno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Aluno");
        setResizable(false);

        btnSalvarAluno.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnSalvarAluno.setText("Salvar");
        btnSalvarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAlunoActionPerformed(evt);
            }
        });

        jtfNomeAluno.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfNomeAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeAlunoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Nome:");

        btnCancelarAluno.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnCancelarAluno.setText("Cancelar");
        btnCancelarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAlunoActionPerformed(evt);
            }
        });

        jtfIdAluno.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfIdAluno.setEnabled(false);
        jtfIdAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIdAlunoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(btnSalvarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jtfIdAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfNomeAluno)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfIdAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlunoActionPerformed
        if (mainView.editarSalvar.equals("salvar")) {
            salvarAluno();
            dispose();
        } else if (mainView.editarSalvar.equals("editar")) {
            editarAluno();
        }
    }//GEN-LAST:event_btnSalvarAlunoActionPerformed

    private void jtfNomeAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeAlunoActionPerformed

    private void btnCancelarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAlunoActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarAlunoActionPerformed

    private void jtfIdAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIdAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIdAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlunoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlunoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlunoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlunoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlunoView().setVisible(true);
            }
        });
    }
    
    private void salvarAluno() {
        if (jtfNomeAluno.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo vazio!", "ATENÇÃO",
                    JOptionPane.WARNING_MESSAGE);
        } else if (jtfNomeAluno.getText().length() >= 50) {
            JOptionPane.showMessageDialog(null, "Campo nome excede o limite de 50 caracteres!", "ATENÇÃO",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            alunoModel.setNomeAluno(jtfNomeAluno.getText().toUpperCase());
            if (alunoController.salvarAlunoController(alunoModel) > 0) {
                JOptionPane.showMessageDialog(null, "Aluno cadastrado com sucesso", "ATENÇÃO",
                        JOptionPane.INFORMATION_MESSAGE);
                mainView.listarAlunos();
            } else {
                JOptionPane.showMessageDialog(null, "Aluno não cadastrado", "ATENÇÃO",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }
    
    private void editarAluno() {
        if (jtfNomeAluno.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo vazio!", "ATENÇÃO",
                    JOptionPane.WARNING_MESSAGE);
        } else if (jtfNomeAluno.getText().length() >= 50) {
            JOptionPane.showMessageDialog(null, "Campo nome excede o limite de 50 caracteres!", "ATENÇÃO",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            alunoModel.setNomeAluno(jtfNomeAluno.getText().toUpperCase());
            if (alunoController.atualizarAlunoController(alunoModel)) {
                JOptionPane.showMessageDialog(null, "Aluno atualizado com sucesso", "ATENÇÃO",
                        JOptionPane.INFORMATION_MESSAGE);
                mainView.listarAlunos();
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Aluno não atualizado", "ATENÇÃO",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }
    
    public void setAlunoModel(AlunoModel aluno) {
        this.alunoModel = aluno;
        jtfIdAluno.setText(this.alunoModel.getCodigoAluno().toString());
        jtfNomeAluno.setText(this.alunoModel.getNomeAluno());
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarAluno;
    private javax.swing.JButton btnSalvarAluno;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtfIdAluno;
    private javax.swing.JTextField jtfNomeAluno;
    // End of variables declaration//GEN-END:variables
}
